# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjE4MWY3YzFhMjBmZGMyNDU1M2NkZTRmNmVhYTIyOWIxZGRhYWJjNjYwMjA5Y2YwZTJlNjY3ZDNjOWQ5OTllNDUzODlhMTVmYTM2ZDIzZWMwMzkyNjdkZmFkZjg1Y2JkNjUxNjE4NzBjYWI1YTVlYWQ1YzkyMWU5MjFhOTcxMmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
